services:
  db:
    image: postgres:13
    container_name: airport_db_container
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-airport_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d airport_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: airport_backend_container
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db 
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-airport_db}
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET:-jwt_secret_key}
      PORT: 5000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: airport_frontend_container
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  postgres-data: